services:
  - type: web
    name: lss-portal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn lss_portal.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lss_portal.settings
      - key: PYTHON_VERSION
        value: 3.10
